name       : haskell-shelly
version    : 1.9.0
release    : 1
source     :
    - https://hackage.haskell.org/package/shelly-1.9.0/shelly-1.9.0.tar.gz : 5eb5fd4fc105e218cef6cfa10971d299ad660324e6a6006b8cccc31edf39aace
license    : BSD-3-Clause
component  : programming.haskell
summary    : shell-like (systems) programming in Haskell
description: |
    Shelly provides convenient systems programming in Haskell, similar in spirit to POSIX shells.
builddeps  :
    - haskell-cabal-install
    - haskell-enclosed-exceptions-devel
    - haskell-exceptions-devel
    - haskell-lifted-async-devel
    - haskell-unix-compat-devel
rundeps    :
    - devel:
        - haskell-enclosed-exceptions-devel
        - haskell-exceptions-devel
        - haskell-lifted-async-devel
        - haskell-unix-compat-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
